### ISSUE TITLE
Theme Toggler

### ISSUE THREAD

**Issue by raviikushh** [jellydn/dapp-starter#1065]
### Describe the bug

The Theme Toggler is coming out of the navbar and not looking I can fix it and make some changes with the cards.

### Reproduction

...

### System Info

```Shell
..
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jellydn** [comment]
I guess that's related with this PR https://github.com/jellydn/dapp-starter/pull/1061/files Thanks.
